### ISSUE TITLE
Occasional failures for the `generate:component-statuses` command in CI

### ISSUE THREAD

**Issue by jamieomaguire** [justeattakeaway/pie#1718]
I have noticed this command fail twice in CI today. [Example](https://github.com/justeattakeaway/pie/actions/runs/10491505671/job/29060924336?pr=1716)

Re-running seems to usually fix the issue. However, I have never noticed this failing before.

<img width="1453" alt="Screenshot 2024-08-21 at 16 02 48" src="https://github.com/user-attachments/assets/7e98d0be-fba0-43a0-9920-68f71aa74780">

**Comment by xander-marjoram** [comment]
I've also noticed this issue a few times. It seems to affect the windows build as well as ubuntu.

I'll write a ticket with @siggerzz's suggestion to see if that fixes it.

**Comment by siggerzz** [comment]
This should now be fixed :)
