### ISSUE TITLE
Docs site not deploying

### ISSUE THREAD

**Issue by xander-marjoram** [justeattakeaway/pie#1736]
This has been happening intermittently.

You will see something like this when you try to visit the deployed page.

![2024-08-28 08_59_12](https://github.com/user-attachments/assets/2c4bb60d-7e83-4ca9-a9a6-765678b04bba)

In this instance, it was on one of the Version Packages PRs.

**Comment by xander-marjoram** [comment]
I logged into the Amplify console and noticed that we have lots of stale branches on the pie-docs app. They are almost all from `closed` PRs so there's probably something wrong with the hook that deletes branches when PRs are closed.

**Comment by siggerzz** [comment]
This should now be fixed as the amplify-teardown action is now working 👍🏼
