### ISSUE TITLE
build-windows-node-18/install-build sometimes throws

### ISSUE THREAD

**Issue by raoufswe** [justeattakeaway/pie#761]
I've noticed that the `build-windows-node-18/install-build` workflow throws the following error when I open up a PR/. The error usually goes away if you rerun the failed job

![image](https://github.com/justeattakeaway/pie/assets/28605803/49d79fc8-e406-43fb-a66c-44ca0de792e8)

**Comment by xander-marjoram** [comment]
We only build on Windows with Node 20 so this hasn't been an issue for some time now.
