### ISSUE TITLE
Intermittent failure for pie-modal Percy screenshots

### ISSUE THREAD

**Issue by xander-marjoram** [justeattakeaway/pie#870]
Occasionally some of the visual regression screenshots for pie-modal fail to render the modal, showing an empty page. These either then have to be re-run (which may take multiple attempts) or they are marked as accepted (to save time) but this later means they need to be re-accepted the next time they succeed.

Example builds:
- https://percy.io/4bc223d1/pie-modal/builds/30547282/changed/1688074820
- https://percy.io/4bc223d1/pie-modal/builds/30521091/changed/1687116453
- https://percy.io/4bc223d1/pie-modal/builds/30493097/changed/1685685819
- https://percy.io/4bc223d1/pie-modal/builds/30655768/changed/1693052363
- https://percy.io/4bc223d1/pie-modal/builds/30659763/changed/1693181140

**Comment by ashleynolan** [comment]
@JoshuaNg2332 Are we happy this has been resolved by the delay added to the modal visual tests?
